### ISSUE TITLE
Estimación de los costes

### ISSUE THREAD

**Issue by livortega11** [atilianno/tfm_master_ds#14]
Se incluye la estimación de los costes de la solución que se propone y se detalla la repercusión o retorno que puede aportar.

**Comment by alexsanchezfabre** [comment]
[Planilla de costos.xlsx](https://github.com/atilianno/tfm_master_ds/files/11952699/Planilla.de.costos.xlsx)

Planilla preliminar de costes del proyecto

**Comment by alexsanchezfabre** [comment]
Planilla final de Costes - Entrega 2 - TFM
[Planilla.de.costes.final.xlsx](https://github.com/atilianno/tfm_master_ds/files/12064492/Planilla.de.costes.final.xlsx)

**Comment by alexsanchezfabre** [comment]
Redacción de texto para incluir en el informe

[Estimación de Costes.docx](https://github.com/atilianno/tfm_master_ds/files/12064644/Estimacion.de.Costes.docx)
