### ISSUE TITLE
Elaboración de filtros negativos

### ISSUE THREAD

**Issue by livortega11** [atilianno/tfm_master_ds#15]
Identificar productos que no pertenecen al los artículos target.

**Comment by livortega11** [comment]
Entre las posibles listas de filtros a eliminar del dataframe pueden ser:  "SALSA DE SOJA","SAUCE SOJA", "SAUCE SOJA","BEBIDA DE SOJA", "YAOURT SOJA","YOGURT DE SOJA","GALLETAS","CHOCOLAT","SPAGHETTI","ARROZ Y SOJA","LECHE","MOUSSE","MILK","ACEITE","DESSERT","PAN SOJA","BOISSON SOJA", "GLACE","ML","SAUCE DE SOJA","SAUCE","SALSA","BIBEDA DE SOJA","LAIT SOJA","VIVESOY SOJA","LAIT DE SOJA","YAOURT","POSTRE","MUESLI","YOGUR","BEBIDA","MARGARINA","VINAIGRETTE"

**Comment by fsanchezcl** [comment]
[exclusiones.txt](https://github.com/atilianno/tfm_master_ds/files/12022589/exclusiones.txt)
[TFM_ExclusionDeFrases.zip](https://github.com/atilianno/tfm_master_ds/files/12022591/TFM_ExclusionDeFrases.zip)
